### ISSUE TITLE
Dynamic item list based on state?

### ISSUE THREAD

**Issue by bensinjin** [RangerMauve/react-native-square-grid#4]
I have something along these lines as a render function:

```
    let items = this.state.someBoolean ? this.props.itemsListA : this.state.itemsListB;
    return (
      <View style={styles.container}>
          <SquareGrid
            rows={5}
            columns={6}
            items={items}
            renderItem={(item) => {return (item);}}
          />
        </View>
      );
```

For whatever reason when I set this.state.someBoolean the render function does get re-called as expected but the grid doesn't appear to re-render and reflect the new item list. Is this expected behaviour? Am I doing something wrong?

**Comment by RangerMauve** [comment]
@bensinjin It should be re-rendering, it might be an issue with React not re-rendering the list for some reason. Try adding a `key={this.state.someBoolean}` prop to `SquareGrid` to force it to re-render.

It might be related to #1

**Comment by bensinjin** [comment]
That worked! Thanks... Could you explain the implications?

**Comment by RangerMauve** [comment]
@bensinjin What this will do is force React to create new views for the SquareGrid whenever the key changes, this means that it'll be re-initialized. If you have huge lists, you'll want to minimize the number of times you change the key since all the child components will have to be created from scratch. (Not too big a deal since you'd be creating new nodes if the children are different anyway)
